### ISSUE TITLE
Add Some sentiment datasets

### ISSUE THREAD

**Issue by oxinabox** [JuliaText/CorpusLoaders.jl#13]
Maybe http://thinknook.com/twitter-sentiment-analysis-training-corpus-dataset-2012-09-22/

though that would kinda want porting a twitter tokenizer into word tokenizers.jl
https://github.com/JuliaText/WordTokenizers.jl/issues/3

**Comment by yash270200** [comment]
@oxinabox , This site for Twitter dataset is not loading now. When I started writing code for this it was working but it is not available now it seems. So I am using link and dataset from this http://help.sentiment140.com/for-students . By stanford link cs.stanford.edu/people/alecmgo/trainingandtestdata.zip .
